// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmJkH1doz9zjeOyM63Pxf0pCDVgF58Bjc',
    appId: '1:923083136188:web:008e37b3537e83f25744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    authDomain: 'life-link-86ed1.firebaseapp.com',
    storageBucket: 'life-link-86ed1.appspot.com',
    measurementId: 'G-WNHVC12TX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-fliaPgnwoibiHG4ddCMInCLZL3KibUc',
    appId: '1:923083136188:android:83ccf86e81c7e56e5744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    storageBucket: 'life-link-86ed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaI6N1BPV8npLZaLhF2MCsKVNc37ML7r0',
    appId: '1:923083136188:ios:6a4c2785492c13fc5744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    storageBucket: 'life-link-86ed1.appspot.com',
    iosBundleId: 'com.example.lifeLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaI6N1BPV8npLZaLhF2MCsKVNc37ML7r0',
    appId: '1:923083136188:ios:46abd5f19319b87c5744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    storageBucket: 'life-link-86ed1.appspot.com',
    iosBundleId: 'com.example.lifeLink.RunnerTests',
  );
}
