import 'package:flutter/material.dart';

const Color primaryColor = Color(0xff006245);
const Color whiteColor = Color(0xffffffff);
const Color greyColor = Color(0xff97ADB6);
const Color lightGreyColor = Color(0xffD5DDE0);
const Color darkBlackColor = Color(0xFF000000);
const Color blackColor = Color(0xFF3E4958);
const Color redColor = Color(0xffff0000);
const Color yellowColor = Color(0xffffff00);
const Color blueColor = Color(0xff0000ff);
const Color skyBlueColor = Color(0xff00ccff);
const Color lightBlueColor = Color(0xff1B73EF);
const Color deepBlueColor = Color(0xff1152FD);
const Color greenColor = Color(0xff008000);
const Color offWhiteColor = Color(0xffffd699);
const Color pinkColor = Color(0xffffc0cb);
const Color appTextColor = Color(0xFF17272E);
const Color backgroundColor = Color(0xffF8FBFF);
const Color brownColor = Color(0xff663300);
const Color camelColor = Color(0xffd2a679);
const Color orangeColor = Color(0xffff9933);
const Color parrotColor = Color(0xff66ff33);
const Color maroonColor = Color(0xff990000);
Color appBarColor = primaryColor.withOpacity(0.8);
const Color textFieldFillColor = Color(0xffF7F8F9);
const Color scaffoldColor = Color(0xFFE9FFF6);
