import 'package:flutter/material.dart';

const Color primaryColor = Color(0xff5e17eb);
const Color whiteColor = Color(0xffffffff);
const Color greyColor = Color(0xff4C6772);
const Color lightGrey = Color(0xff93A4AA);
const Color blackColor = Color(0xFF000000);
const Color redColor = Color(0xffff0000);
const Color yellowColor = Color(0xffffff00);
const Color blueColor = Color(0xff0000ff);
const Color greenColor = Color(0xff008000);
const Color offWhiteColor = Color(0xffffd699);
const Color pinkColor = Color(0xffffc0cb);
const Color appTextColor = Color(0xFF17272E);
const Color backgroundColor = Color(0xffF8FBFF);
const Color lightBlueColor = Color(0xff1B73EF);
const Color brownColor = Color(0xff663300);
const Color camelColor = Color(0xffd2a679);
const Color orangeColor = Color(0xffff9933);
const Color skyBlueColor = Color(0xff00ccff);
const Color parrotColor = Color(0xff66ff33);
const Color maroonColor = Color(0xff990000);
Color appBarColor = primaryColor.withOpacity(0.8);
